# Generated by Django 2.1.3 on 2018-12-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_people_photospeople_userface_userinsta_usertinder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertinder',
            name='view_man',
        ),
        migrations.RemoveField(
            model_name='usertinder',
            name='view_woman',
        ),
        migrations.AddField(
            model_name='usertinder',
            name='gender_filter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertinder',
            name='photo',
            field=models.CharField(default='fotografia', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photospeople',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.People'),
        ),
    ]
