# Generated by Django 2.1.3 on 2018-12-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usertinder_fb_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertinder',
            name='fb_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tinder', to='api.UserFace'),
        ),
    ]
