# Generated by Django 2.1.3 on 2018-12-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181204_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertinder',
            name='fb_user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tinder', to='api.UserFace'),
        ),
    ]
